---
layout: cv
title: Mia Smith's CV
---
# Mia Smith
Physicist, Mathematician, Cambridge professor.

<div id="webaddress">
<a href="smi22077@byui.edu">ismi22077@byui.edu</a>
| <a href="https://www.linkedin.com/in/mia-smith-52a565345/">My LinkedIn Page</a>
</div>


## Currently

Standing on the shoulders of giants

### Specialized in

Laws of motion, gravitation, minting coins, disliking [Robert Hooke](http://en.wikipedia.org/wiki/Robert_Hooke)


### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.


## Education

`1654-1660`
__Brigham Young University, Idaho.__

`June 1661 - now`
__Trinity College, Cambridge__

- Sizar



## Awards

`2012`
President, *Royal Society*, London, UK

Associate, *French Academy of Science*, Paris, France



## Publications

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001


## Occupation

`1600`
__Royal Mint__, London

- Warden
- Minted coins

`1600`
__Lucasian professor of Mathematics__, Cambridge University



<!-- ### Footer

Last updated: May 2013 -->